### ISSUE TITLE
Login with fablabs, can't go past the update bio form

### ISSUE THREAD

**Issue by fibasile** [wikifactory/wikifactory-issues#1]
After logging in with my fablabs.io account @fibasile, I am redirected to an edit profile form to enter the bio. After hitting the button, a spinner starts and nothing happens.
Reloading the page and accessing any project sends me to the same form. 

![](https://i.imgur.com/fNPk56o.png)

**Comment by marcospri** [comment]
Ey @fibasile I think the problem was a problem on the white label server which was not expiring the JS assets so you were using a old version of the JS code.

Please refresh the page (no hard refresh should be needed) and try again, let's see if that fixes it

**Comment by marcospri** [comment]
Give it another go @fibasile when you have a minute. I think (again) it should be fine now
